name: zonmw
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pandas=1.2.1
  - scikit-learn=0.23.2
  - openpyxl=3.0.6
  - spacy=3.0.3
  - jupyter
  - jupyterlab=2.2.6
  - ipykernel=5.3.4
