name: zonmw
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.5
  - pandas=1.3.0
  - scikit-learn=0.23.2
  - openpyxl=3.0.6
  - spacy=3.0.3
  - jupyter=1.0.0
  - jupyterlab=2.2.6
  - ipykernel=5.3.4
  - matplotlib=3.3.4
  - tqdm=4.49.0
  - pytorch=1.8.1
  - cudatoolkit=10.2
  - requests=2.25.1
  - tensorboardx=2.3
  - wandb=0.10.33
  - pip=20.3.3
  - pip:
      - simpletransformers=0.61.9
