name: zonmw
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.5
  - pandas=1.2.1
  - scikit-learn=0.23.2
  - openpyxl=3.0.6
  - spacy=3.0.3
  - jupyter
  - jupyterlab=2.2.6
  - ipykernel=5.3.4
  - matplotlib=3.3.4
  - tqdm=4.59
  - pytorch=1.8
  - cudatoolkit=10.2
  - requests=2.25
  - tensorboardx
  - wandb
  - pip
  - pip:
      - simpletransformers
